apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
      annotations:
        # Enable Prometheus support: the Spring Boot app automatically exposes metrics.
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
      - name: app
        # FIXME: update the image name with its tag.
        image: ghcr.io/mosehsah/spring-petclinic:1
        resources:
          limits:
            memory: 1Gi
        # Spring Boot provides health probes that you can use with Kubernetes:
        # this instance will not receive incoming traffic until the pod is up and running.
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: spring-petclinic
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    tier: app
  type: LoadBalancer